image: "rust:latest"

#   - apt-get install -yqq --no-install-recommends build-essential
before_script:
    - apt-get update -yqq
    - apt-get install -yqq --no-install-recommends gcc-arm-none-eabi

# Use cargo to test the project
test:cargo:

  script:
    - rustc --version && cargo --version  # Print version info for debugging
    - cargo check --verbose
    - cargo check --examples --verbose
