image: "rustlang/rust:nightly"

variables:
  CARGO_HOME: $CI_PROJECT_DIR/.cargo
  DEBIAN_FRONTEND: noninteractive

before_script:
    - apt-get update -yqq
    - apt-get install -yqq libclang-dev
    - apt-get install -yqq gcc-arm-none-eabi

test:cargo:
  script:
    - rustc --version && cargo --version  # Print version info for debugging
    - cargo fmt -- --check
    - cargo build
    - cargo build --examples
  cache:
    paths:
      - .cargo
