image: "rustlang/rust:nightly"

variables:
  CARGO_HOME: $CI_PROJECT_DIR/.cargo
  DEBIAN_FRONTEND: noninteractive

#   - apt-get install -yqq --no-install-recommends build-essential
before_script:
    - apt-get update -yqq
    - apt-get install -yqq --no-install-recommends gcc-arm-none-eabi

test:cargo:
  script:
    - rustc --version && cargo --version  # Print version info for debugging
    - cargo check --verbose
    - cargo check --examples --verbose
  cache:
    paths:
      - .cargo
